name: cognitiveroulletegame
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  intl: any
  provider:
  fl_chart:
  sqflite: ^2.3.0
  path: ^1.8.3
  http: ^1.1.2
  uuid: ^4.3.2
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  connectivity_plus: ^5.0.2
  shared_preferences: ^2.2.2
  flutter_native_splash: 2.3.10
  introduction_screen: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_native_splash:
  color: "#E4F3FA"
  image: assets/splash.png
  android: true
  ios: true
  web: false

